import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { createReel, getSocialNotes, getSocialProfile, listCallSignals, listConversations, listFriendRequests, listMessages, listReels, respondToFriendRequest, saveSocialNote, saveSocialProfile, searchSocialProfiles, sendCallSignal, sendFriendRequest, sendMessage, toggleFollow } from "../controllers/socialController.js";

export const socialRoutes = Router();
socialRoutes.use(requireAuth);
socialRoutes.get("/profile", getSocialProfile);
socialRoutes.put("/profile", saveSocialProfile);
socialRoutes.get("/notes", getSocialNotes);
socialRoutes.put("/notes", saveSocialNote);
socialRoutes.get("/search", searchSocialProfiles);
socialRoutes.get("/requests", listFriendRequests);
socialRoutes.post("/users/:userId/request", sendFriendRequest);
socialRoutes.post("/requests/:requestId/respond", respondToFriendRequest);
socialRoutes.post("/users/:userId/follow", toggleFollow);
socialRoutes.get("/reels", listReels);
socialRoutes.post("/reels", createReel);
socialRoutes.get("/conversations", listConversations);
socialRoutes.get("/conversations/:conversationId/messages", listMessages);
socialRoutes.post("/users/:userId/messages", sendMessage);
socialRoutes.get("/calls/signals", listCallSignals);
socialRoutes.post("/users/:userId/calls/signals", sendCallSignal);
