import express, { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { addSocialReelComment, createReel, createUploadedReel, getSocialNotes, getSocialProfile, getSocialReelComments, getSocialReelMedia, getTypingStatus, listCallSignals, listConversations, listFriendRequests, listMessages, listReels, respondToFriendRequest, saveSocialNote, saveSocialProfile, searchSocialProfiles, sendCallSignal, sendFriendRequest, sendMessage, setTypingStatus, toggleFollow, toggleReelLike } from "../controllers/socialController.js";

export const socialRoutes = Router();
socialRoutes.use(requireAuth);
socialRoutes.get("/profile", getSocialProfile);
socialRoutes.put("/profile", saveSocialProfile);
socialRoutes.get("/notes", getSocialNotes);
socialRoutes.put("/notes", saveSocialNote);
socialRoutes.get("/search", searchSocialProfiles);
socialRoutes.get("/requests", listFriendRequests);
socialRoutes.post("/users/:userId/request", sendFriendRequest);
socialRoutes.post("/requests/:requestId/respond", respondToFriendRequest);
socialRoutes.post("/users/:userId/follow", toggleFollow);
socialRoutes.get("/reels", listReels);
socialRoutes.post("/reels", createReel);
socialRoutes.post("/reels/upload", express.raw({ type:["image/jpeg", "image/png", "image/webp", "video/mp4", "video/webm", "video/quicktime", "video/3gpp"], limit:"20mb" }), createUploadedReel);
socialRoutes.get("/reels/:reelId/media", getSocialReelMedia);
socialRoutes.post("/reels/:reelId/like", toggleReelLike);
socialRoutes.get("/reels/:reelId/comments", getSocialReelComments);
socialRoutes.post("/reels/:reelId/comments", addSocialReelComment);
socialRoutes.get("/conversations", listConversations);
socialRoutes.get("/conversations/:conversationId/messages", listMessages);
socialRoutes.get("/conversations/:conversationId/typing", getTypingStatus);
socialRoutes.post("/users/:userId/typing", setTypingStatus);
socialRoutes.post("/users/:userId/messages", sendMessage);
socialRoutes.get("/calls/signals", listCallSignals);
socialRoutes.post("/users/:userId/calls/signals", sendCallSignal);
